### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by jldinh** [jldinh/multicell#1]
Copied here on behalf of @gweeish

> I'm trying to install multicell and in the process, I'm trying to install OpenAlea. However, I'm having the following issue with the 'python multisetup.py develop --user'. The issue is as follows:
> 
> 'Error processing line 1 of /Users/gweeish/.local/lib/python3.7/site-packages/OpenAlea.SConsX-nspkg.pth:
> 
> Traceback (most recent call last):
> File "/Users/gweeish/.pyenv/versions/3.7.5/lib/python3.7/site.py", line 168, in addpackage
> exec(line)
> File "", line 1, in
> File "", line 580, in module_from_spec
> AttributeError: 'NoneType' object has no attribute 'loader'
> 
> Remainder of file ignored
> Error processing line 1 of /Users/gweeish/.local/lib/python3.7/site-packages/openalea.deploy-nspkg.pth:
> 
> Traceback (most recent call last):
> File "/Users/gweeish/.pyenv/versions/3.7.5/lib/python3.7/site.py", line 168, in addpackage
> exec(line)
> File "", line 1, in
> File "", line 580, in module_from_spec
> AttributeError: 'NoneType' object has no attribute 'loader'
> 
> Remainder of file ignored
> Install OpenAlea.Deploy first
> Install OpenAlea.Deploy first
> cannot import name 'Multisetup' from 'multisetup' (/Users/gweeish/openalea/multisetup.py)
> cannot import name 'Multisetup' from 'multisetup' (/Users/gweeish/openalea/multisetup.py)
> Traceback (most recent call last):
> File "multisetup.py", line 73, in
> main()
> File "multisetup.py", line 68, in main
> mysetup = Multisetup(curdir='.', commands=args, packages=dirs)
> NameError: name 'Multisetup' is not defined'
> 
> Any help would be greatly appreciated.
> 
> Thank you!

**Comment by jldinh** [comment]
@gweeish I think the problem stems from the fact that you are using Python 3, while multicell was made for Python 2.

That's because 5 years ago, when `multicell` and `openalea` were made, Python 2 was still very common (if not the most common), but this is no longer the case, and I haven't worked on this project since then.

What OS are you using? Are you able to install Python 2?

**Comment by gweeish** [comment]
Hi, 

Thank you for getting back to me. I am able to run Python 2 but am now running into this issue while installing openalea using the multisetup.py script:

NameError: global name 'Multisetup' is not defined

Thank you.

**Comment by jldinh** [comment]
Sorry, it looks like things changed a lot since I wrote the library.
I will need to put together new install instructions.
It might take a while, because the distribution methods of some of the dependencies seem to have changed.

**Comment by gweeish** [comment]
Hi @jldinh ,

Thank you for letting me know. I will definitely be watching this space. =)

**Comment by jldinh** [comment]
Hi @gweeish ,

I just updated the install instructions with specific git commits to checkout, to make sure you have the same versions as I was using when the library was made.

I also provided a new download link for vplants, as the original went down.

Let me know if you encounter other issues.
